package com.zbinfinn.flangidea

import com.intellij.psi.tree.IElementType

class FlangTokenType(debugName: String) : IElementType(debugName, FlangLanguage)

object FlangTokenTypes {
    val KEYWORD = FlangTokenType("KEYWORD")
    val IDENTIFIER = FlangTokenType("IDENTIFIER")
    val NUMBER = FlangTokenType("NUMBER")
    val STRING = FlangTokenType("STRING")
    val STYLED_STRING = FlangTokenType("STYLED_STRING")
    val LINE_COMMENT = FlangTokenType("LINE_COMMENT")
    val BLOCK_COMMENT = FlangTokenType("BLOCK_COMMENT")
    val OPERATOR = FlangTokenType("OPERATOR")
    val PUNCTUATION = FlangTokenType("PUNCTUATION")
    val LBRACE = FlangTokenType("LBRACE")
    val RBRACE = FlangTokenType("RBRACE")
    val LPAREN = FlangTokenType("LPAREN")
    val RPAREN = FlangTokenType("RPAREN")
    val LBRACKET = FlangTokenType("LBRACKET")
    val RBRACKET = FlangTokenType("RBRACKET")
    val ANNOTATION = FlangTokenType("ANNOTATION")
    val ENUM_SHORTHAND = FlangTokenType("ENUM_SHORTHAND")
    val EMIT_CONTENT = FlangTokenType("EMIT_CONTENT")
    val BAD_CHARACTER = FlangTokenType("BAD_CHARACTER")
    val FILE = FlangTokenType("FILE")

    val AT = FlangTokenType("AT")
    val INLINE = FlangTokenType("INLINE")
    val PACKAGE = FlangTokenType("PACKAGE")
    val IMPORT = FlangTokenType("IMPORT")
    val PRIVATE = FlangTokenType("PRIVATE")
    val PC = FlangTokenType("PC")
    val FN = FlangTokenType("FN")
    val EMIT = FlangTokenType("EMIT")
    val VAL = FlangTokenType("VAL")
    val VAR = FlangTokenType("VAR")
    val TRUE = FlangTokenType("TRUE")
    val FALSE = FlangTokenType("FALSE")
    val RETURN = FlangTokenType("RETURN")
    val START = FlangTokenType("START")
    val IF = FlangTokenType("IF")
    val ELSE = FlangTokenType("ELSE")
    val FOR = FlangTokenType("FOR")
    val IN = FlangTokenType("IN")
    val WHILE = FlangTokenType("WHILE")
    val WHEN = FlangTokenType("WHEN")
    val AS = FlangTokenType("AS")
    val STRUCT = FlangTokenType("STRUCT")
    val INTERFACE = FlangTokenType("INTERFACE")
    val ENUM = FlangTokenType("ENUM")
    val IMPL = FlangTokenType("IMPL")
    val OBJECT = FlangTokenType("OBJECT")
    val ARGS = FlangTokenType("ARGS")
    val TAGS = FlangTokenType("TAGS")

    val ARROW = FlangTokenType("ARROW")
    val EQ = FlangTokenType("EQ")
    val EQ_EQ = FlangTokenType("EQ_EQ")
    val NOT_EQ = FlangTokenType("NOT_EQ")
    val LT_EQ = FlangTokenType("LT_EQ")
    val GT_EQ = FlangTokenType("GT_EQ")
    val AND_AND = FlangTokenType("AND_AND")
    val OR_OR = FlangTokenType("OR_OR")
    val DOT_DOT = FlangTokenType("DOT_DOT")
    val AMP = FlangTokenType("AMP")
    val PLUS = FlangTokenType("PLUS")
    val MINUS = FlangTokenType("MINUS")
    val STAR = FlangTokenType("STAR")
    val SLASH = FlangTokenType("SLASH")
    val PERCENT = FlangTokenType("PERCENT")
    val DOT = FlangTokenType("DOT")
    val COMMA = FlangTokenType("COMMA")
    val COLON = FlangTokenType("COLON")
    val SEMI = FlangTokenType("SEMI")
    val BACKTICK = FlangTokenType("BACKTICK")
    val DOLLAR = FlangTokenType("DOLLAR")
    val LT = FlangTokenType("LT")
    val GT = FlangTokenType("GT")
}
